# Generated by Django 3.2.1 on 2021-05-06 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('publish_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
