# Generated by Django 3.2.1 on 2021-05-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(choices=[('Python', 'Python'), ('Django', 'Django'), ('Postgresql', 'Postgresql'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('Bootstrap', 'Bootstrap'), ('Backend', 'Backend'), ('Frontend', 'Frontend'), ('Full-Stack', 'Full-Stack'), ('JavaScript', 'JavaScript'), ('Web Design', 'Web Design'), ('Roiback', 'Roiback')], default='Other', max_length=100),
        ),
    ]
